# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{swfmill_ruby}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["tmtysk"]
  s.date = %q{2010-03-07}
  s.description = %q{SwfmillRuby
===========

SwfmillRuby is a utility-classes to use Swfmill(http://swfmill.org) via Ruby.
This library is assumed to use to fiddle with the SWF published as FlashLite 1.1 - most popular version among mobile phone in Japan.

* features
  * SwfmillUtil::Swfmill
    * calling swfmill-program(xml2swf, swf2xml) from ruby.
  * SwfmillUtil::Swf
    * accessing to images(Magick::Image) included in Swf. (Swf#images)
    * replacing images and texts included in Swf.
      * supported tags: DefineBitsLossless, DefineBitsLossless2, DefineBitsJPEG2 and DefineEditText.
      * converting DefineBitsLossless, DefineBitsLossless2, DefineBitsJPEG2 <=> Magick::Image
    * controlling movieclips in Swf (alpha version)
      * accessing to movieclips as SwfmillUtil::DefineSprite in Swf. (Swf#movieclips)
      * accessing to movieclips by instance-name placed on stage. (Swf#movieclip_ids_named)
      * replacing movieclips with referred shapes, images and texts.
      * making partial xml meaning movieclip from Swf to use for replacing by DefineSprite#[]=. (DefineSprite#partialize)
      * making template text based on original xml to use for replacing by String#gsub. (DefineSprite#templatize)
      * adjusting referred object_ids on replace movieclips.
    * writing out re-generated Swf. (Swf#write)

Requirements
============

 * swfmill 0.2.12 or greater
   - patched supporting CP932 encoding
     http://dsas.blog.klab.org/archives/51174693.html .. patched it on rev.278 (version 0.3.0.1)
   - patched supporting DefineBitsLossless format=3
     http://cyanogen.dynsite.net/~raia/diary/20090728.html#p01
 * ImageMagick 6.3.7 or greater
 * rubygems and rmagick(2.8.0 or greater) library
 * LibXML2 and libxml-ruby(0.9.7)

Usage
=====

First, Set constant SWFMILL in lib/swfmill.rb to path to swfmill-program for your environment.
Then,

 $ gem install jeweler
 $ rake build
 $ rake install

See sample/*.rb files for sample.

Thanks
======

* http://swfmill.org/
* Great patch-program for swfmill provided by KLab,Inc.
* Sample GIF image is provided by ICHIGO-APORO.
* Supporting 32-bit PNG by hokaccha-san.
* Supporting DefineBitsLossless by muraoka17-san.

Copyright (c) 2008-2010 tmtysk.
    released under the GNU GENERAL PUBLIC LICENSE Version 2.
    See COPYING for details.
}
  s.email = %q{tmtysk@gmail.com}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "COPYING",
     "README",
     "Rakefile",
     "VERSION",
     "doc/classes/SwfmillUtil.html",
     "doc/classes/SwfmillUtil/DefineBitsJPEG2.html",
     "doc/classes/SwfmillUtil/DefineBitsJPEG2.src/M000016.html",
     "doc/classes/SwfmillUtil/DefineBitsJPEG2.src/M000017.html",
     "doc/classes/SwfmillUtil/DefineBitsLossless.html",
     "doc/classes/SwfmillUtil/DefineBitsLossless.src/M000006.html",
     "doc/classes/SwfmillUtil/DefineBitsLossless.src/M000007.html",
     "doc/classes/SwfmillUtil/DefineBitsLossless2.html",
     "doc/classes/SwfmillUtil/DefineBitsLossless2.src/M000018.html",
     "doc/classes/SwfmillUtil/DefineBitsLossless2.src/M000019.html",
     "doc/classes/SwfmillUtil/DefineSprite.html",
     "doc/classes/SwfmillUtil/DefineSprite.src/M000008.html",
     "doc/classes/SwfmillUtil/DefineSprite.src/M000009.html",
     "doc/classes/SwfmillUtil/DefineSprite.src/M000010.html",
     "doc/classes/SwfmillUtil/DefineSprite.src/M000011.html",
     "doc/classes/SwfmillUtil/DefineSprite.src/M000012.html",
     "doc/classes/SwfmillUtil/DefineSprite.src/M000013.html",
     "doc/classes/SwfmillUtil/DefineSprite.src/M000014.html",
     "doc/classes/SwfmillUtil/ReplacableResources.html",
     "doc/classes/SwfmillUtil/ReplacableResources.src/M000015.html",
     "doc/classes/SwfmillUtil/ReplaceTargetNotFoundError.html",
     "doc/classes/SwfmillUtil/Swf.html",
     "doc/classes/SwfmillUtil/Swf.src/M000003.html",
     "doc/classes/SwfmillUtil/Swf.src/M000004.html",
     "doc/classes/SwfmillUtil/Swf.src/M000005.html",
     "doc/classes/SwfmillUtil/Swfmill.html",
     "doc/classes/SwfmillUtil/Swfmill.src/M000001.html",
     "doc/classes/SwfmillUtil/Swfmill.src/M000002.html",
     "doc/created.rid",
     "doc/files/lib/swf_rb.html",
     "doc/files/lib/swfmill_rb.html",
     "doc/files/sample/partialize_sample_rb.html",
     "doc/files/sample/regenerate_sample_rb.html",
     "doc/files/sample/repl_image_sample_rb.html",
     "doc/files/sample/repl_mc_sample_rb.html",
     "doc/files/sample/swfmill_sample_rb.html",
     "doc/files/sample/templatize_sample_rb.html",
     "doc/fr_class_index.html",
     "doc/fr_file_index.html",
     "doc/fr_method_index.html",
     "doc/index.html",
     "doc/rdoc-style.css",
     "lib/swf.rb",
     "lib/swfmill.rb",
     "sample/data/3.gif",
     "sample/data/6.jpg",
     "sample/data/animation_partial.xml",
     "sample/data/animation_partial_gsub.xml",
     "sample/data/animation_template_gsub.xml",
     "sample/data/bg.jpg",
     "sample/data/flymelongirl.gif",
     "sample/data/regenerated.swf",
     "sample/data/regenerated_gsub.swf",
     "sample/data/replaced_image.swf",
     "sample/data/replaced_mc.swf",
     "sample/data/sample_original.swf",
     "sample/data/sample_original2.swf",
     "sample/data/sample_template.xml",
     "sample/data/swfmill_sample.xml",
     "sample/partialize_sample.rb",
     "sample/regenerate_sample.rb",
     "sample/repl_image_sample.rb",
     "sample/repl_mc_sample.rb",
     "sample/swfmill_sample.rb",
     "sample/templatize_sample.rb",
     "swfmill_ruby.gemspec"
  ]
  s.homepage = %q{http://github.com/tmtysk/swfmill_ruby}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{utility-classes to use Swfmill(http://swfmill.org) via Ruby.}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rmagick>, [">= 2.8.0"])
      s.add_runtime_dependency(%q<libxml-ruby>, [">= 0.9.7"])
    else
      s.add_dependency(%q<rmagick>, [">= 2.8.0"])
      s.add_dependency(%q<libxml-ruby>, [">= 0.9.7"])
    end
  else
    s.add_dependency(%q<rmagick>, [">= 2.8.0"])
    s.add_dependency(%q<libxml-ruby>, [">= 0.9.7"])
  end
end

